#!/bin/bash

echo "[SpeedOS] Aplicando configuração para Ubuntu 24.04 (noble)..."

lb config \
    --mode ubuntu \
    --distribution noble \
    --architecture amd64 \
    --debian-installer live \
    --binary-images iso-hybrid \
    --archive-areas "main restricted universe multiverse" \
    --bootappend-live "boot=live components username=speedos" \
    --mirror-bootstrap http://archive.ubuntu.com/ubuntu/ \
    --mirror-chroot http://archive.ubuntu.com/ubuntu/ \
    --mirror-binary http://archive.ubuntu.com/ubuntu/ \
    --mirror-debian-installer http://archive.ubuntu.com/ubuntu/

echo "[SpeedOS] Configuração carregada com sucesso!"