#!/bin/bash

lb config \
    --mode ubuntu \
    --distribution noble \
    --architecture amd64 \
    --bootappend-live "boot=live components username=speedos" \
    --debian-installer live \
    --binary-images iso-hybrid \
    --archive-areas "main restricted universe multiverse"
