[Global]

distribution: "SpeedOS"
desktop: "XFCE"

defaultLanguage: "pt_BR"
defaultKeyboardLayout: "br"

modules: [
    "welcome",
    "locale",
    "keyboard",
    "partition",
    "mount",
    "unpackfs",
    "users",
    "networkcfg",
    "bootloader",
    "summary",
    "finished"
]

oem: false

[Welcome]
welcome: "Bem-vindo ao SpeedOS"
welcome_image: "/usr/share/calamares/images/welcome.png"

[Finished]
restart_now: true
restart_command: "reboot"