name: Build SpeedOS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar dependências (live-build atualizado)
        run: |
          sudo apt update
          sudo apt install -y debootstrap ca-certificates gnupg
          echo "deb [trusted=yes] http://archive.ubuntu.com/ubuntu noble main universe multiverse restricted" | sudo tee /etc/apt/sources.list.d/noble.list
          sudo apt update
          sudo apt install -y live-build

      - name: Tornar auto/config executável
        run: chmod +x config/live-build/auto/config

      - name: Build SpeedOS ISO
        run: |
          cd config/live-build
          sudo lb clean --purge
          sudo rm -rf cache/ chroot/ binary/ local/ .build/
          sudo ./auto/config
          sudo lb build

      - name: Upload da ISO gerada
        uses: actions/upload-artifact@v4
        with:
          name: speedos-iso
          path: '**/*.iso'